#include <stdio.h>

/*
 *
 * The FCS-16 generator polynominal: x**0 + x**5 + x**12 + x **16
 */
#define P 0x8408

/*
 * Generate a FCS-16 table.
 * from RFC 1662.
 */
int main(void) {
    register unsigned int b, v;
    register int i;

    printf("#include \"fcstable.h\"\n");
    printf("// This file is generated by fcstable_gen\n");
    printf("u16 fcstab[256] = {");
    for (b = 0; ; ) {
        if (b % 8 == 0) {
            printf("\n");
        }
        v = b;
        for (i = 8; i--; ) {
            v = v & 1 ? (v >> 1) ^ P : v >> 1;
        }

        printf("\t0x%04x", v & 0xffff);
        if (++b == 256) {
            break;
        }
        printf(",");
    }
    printf("\n};\n");

    return 0;
}
